config/routes.rb
Rails.application.routes.draw do
  resources :albums
  get 'albums/:id/show_photo' => 'albums#show_photo', as: 'show_photo'

  root 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :photos, dependent: :destroy
	validates_presence_of :title
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :album
	mount_uploader :image, ImageUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy, :show_photo]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  def show_photo
    @photo = Photo.find(params[:photo_id])
  end

  # GET /albums/new
  def new
    @album = Album.new
    @direct_mode = params[:direct_mode]
  end

  # GET /albums/1/edit
  def edit
    @direct_mode = params[:direct_mode]
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        store_photos
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        delete_photos
        store_photos
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title)
    end

    def store_photos
      photos = params[:album][:photos]
      photos.each{|photo| @album.photos.create(image: photo)} if photos
    end

    def delete_photos
      @album.photos.each do |photo|
        photo.destroy if params[photo.id.to_s] == "delete"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%= cloudinary_js_config %>
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :photos, @direct_mode ? "Add new photos (Client-side)" : "Add new photos (Server-side)" %><br>
    <% if @direct_mode %>
      <%= f.cl_image_upload :photos, multiple: true %>
    <% else %>
      <%= f.file_field :photos, multiple: true %>
    <% end %>
  </div>

  <% if @direct_mode %>
    <div id="progress_bar_box">
      <div id="progress_bar"></div>
      <div id="progress_percents"></div>
    </div>
    <div id="preview_images"></div>
  <% end %>

  <div>
    <% if @album.photos.any? %>
      Delete photos<br /><br />
      <%= check_box_tag "select_all" %> Select all <br />
      <% @album.photos.each do |photo| %>
        <%= check_box_tag photo.id, "delete" %>
        <%= cl_image_tag(photo.image.thumb.url) %>
        <br />
      <% end %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit data: {confirm: "Are you sure?"} %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    $('#select_all').click(function(event) {  //on click 
      if(this.checked) { // check select status
        $('form input:checkbox').each(function() { //loop through each checkbox
          this.checked = true;  //select all checkboxes with class "checkbox1"               
        });
      }else{
        $('form input:checkbox').each(function() { //loop through each checkbox
          this.checked = false; //deselect all checkboxes with class "checkbox1"                       
        });         
      }
    });
    $('.cloudinary-fileupload').cloudinary_fileupload().on('cloudinarydone', function(e, data){
      $('#preview_images').append($.cloudinary.image(data.result.public_id, {width: 50, height: 50, crop: "fill"}));
    })
    .on('cloudinaryprogressall', function(e, data){
      $('#progress_bar_box').show();
      var percents = Math.round((data.loaded * 100.0) / data.total) + '%'
      $('#progress_percents').text(percents)
      $('#progress_bar').css('width', percents); 
    })
    .on('fileuploadstop', function(){
      $('#progress_bar_box').hide();
    });
  });
</script>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Albums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= cl_image_tag(album.photos.first.image.thumb.url) if album.photos.any? %></td>
        <td><%= album.title %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit (Server-side)', edit_album_path(album) %></td>
        <td><%= link_to 'Edit (Client-side)', edit_album_path(album, direct_mode: true) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album (Server-side upload)', new_album_path %><br />
<%= link_to 'New Album (Client-side upload)', new_album_path(direct_mode: true) %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<% if @album.photos.any? %>
	<p>
		<% @album.photos.each do |photo| %>
			<%= link_to cl_image_tag(photo.image.thumb.url), show_photo_path(photo_id: photo) %>
		<% end -%>
	</p>
<% end %>

<%= link_to 'Edit (Server-side)', edit_album_path(@album) %> |
<%= link_to 'Edit (Client-side)', edit_album_path(@album, direct_mode: true) %> |
<%= link_to 'Back', albums_path %>

app/views/albums/show_photo.html.erb
<%= link_to "Back to Album", album_path %><br />
<%= cl_image_tag(@photo.image.url) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CloudinaryMultipleUploads</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>